spring:
  cloud:
    circuitbreaker:
      resilience4j:
        instances:
          product-cb:
            slidingWindowSize: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 30s
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            # Timeout da hata sayılsın
            slowCallDurationThreshold: 2s
            slowCallRateThreshold: 50
            # Connection refused da hata sayılsın
            recordExceptions:
              - java.lang.Exception
          customer-cb:
            slidingWindowSize: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 30s
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            slowCallDurationThreshold: 2s
            slowCallRateThreshold: 50
            recordExceptions:
              - java.lang.Exception
          order-cb:
            slidingWindowSize: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 30s
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            slowCallDurationThreshold: 2s
            slowCallRateThreshold: 50
            recordExceptions:
              - java.lang.Exception