spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/customerdb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

info:
  app:
    name: Customer Service
    version: 1.0.0